# 指定日志存储位置
logging:
  path: /tmp/rabbitMQDemo
# spring配置
spring:
  rabbitmq:
    addresses: 10.159.63.17
    port: 5672
    username: haieradmin
    password: haieradmin
    virtual-host: /
    publisher-confirms: true # ack
    publisher-returns: true  # ack
    template:
      mandatory: true
    listener:
      simple:
        concurrency: 2 # 最小消息监听线程数
        max-concurrency: 2 # 最大消息监听线程数
        retry:
          enabled: true # 重试机制，默认重试3次
