# 指定日志存储位置
logging:
  path: /tmp/rabbitMQDemo
# spring配置
spring:
  rabbitmq:
    addresses: 127.0.0.1:5672,127.0.0.1:5673,127.0.0.1:5674
    username: oldadmin
    password: oldadmin
    virtual-host: /
    publisher-confirms: true # ack
    publisher-returns: true  # ack
    template:
      mandatory: true
    listener:
      simple:
        concurrency: 2 # 最小消息监听线程数
        max-concurrency: 2 # 最大消息监听线程数
        retry:
          enabled: true # 重试机制，默认重试3次
